# Generated by Django 4.0.3 on 2023-03-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_location_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='weather',
            field=models.URLField(null=True),
        ),
    ]
