# Generated by Django 4.0.3 on 2023-03-23 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_location_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='weather',
        ),
    ]
